apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service-api
  labels:
    app: transaction-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service-api
  template:
    metadata:
      labels:
        app: transaction-service-api
    spec:
      containers:
      - name: transaction-service-api
        image: catalystcontainerregistry.azurecr.io/transactions/transaction-service-api:1.0.1
        env:
        - name: CONFIG__EVENTSTORESINGLENODEHOST
          value: "transactionservice-persistence"
        - name: CONFIG__MONGODBCONNECTIONSTRING
          value: "mongodb://transactionservice-persistence:27017"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service-api
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: transaction-service-api
---
apiVersion: v1
kind: Service
metadata:
  name: transactionservice-api-external
spec:
  ports:
  - port: 80
    name: web1
  selector:
    app: transaction-service-api
  type: LoadBalancer


